server:
  port: 0

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test-task
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  flyway:
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

entity-error-code:
  not-found: 404
  not-created: 422
  not-updated: 422
  not-login: 433
  not-approved: 444

jwt:
  token:
    secret: test-task
    subject: details
    expired: 120
    issuer: me