server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: file-storage
          uri: lb://file-storage
          predicates:
            - Path=/file-storage/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
      default-filters:
        - AuthenticationFilter

error-code:
  auth: 401
  invalid-token: 499

jwt:
  token:
    secret: test-task
    subject: details
    expired: 120
    issuer: me
