server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: file-storage
          uri: lb://file-storage
          predicates:
            - Path=/file-storage/**

